### get
GET http://localhost:8080/houses
###
GET http://localhost:8080/houses/20


### 
GET http://localhost:8080/houses/city/Cali


### post 
POST http://localhost:8080/houses
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4xMjM=

{
    "city": "Medellisadasn",
    "price": 250000.0,
    "bedrooms": 3,
    "bathrooms": 2
}

### put
PUT http://localhost:8080/houses/9
Content-Type: application/json

{
    "city": "Bogota",
    "price": 300000.0,
    "bedrooms": 4,
    "bathrooms": 3
}

### delete
DELETE http://localhost:8080/houses/9
Authorization: Basic YWRtaW46YWRtaW4xMjM=


